### ISSUE TITLE
Firebase Authentication with Microsoft provider throws Exception 

### ISSUE THREAD

**Issue by xanscale** [microsoft/WSA#432]
### Steps to reproduce

`Firebase.auth.startActivityForSignInWithProvider(this, OAuthProvider.newBuilder("microsoft.com").build())`

### ✔️ Expected Behavior

should open Browser throught `ACTION_VIEW` and return on app when finished

### ❌ Actual Behavior

```
14:58:55.220  W  com.google.firebase.auth.FirebaseAuthWebException: The web operation was canceled by the user.
14:58:55.220  W  	at com.google.android.gms.internal.firebase-auth-api.zzaas.zza(com.google.firebase:firebase-auth@@22.1.1:11)
14:58:55.220  W  	at com.google.firebase.auth.internal.zzav.onReceive(com.google.firebase:firebase-auth@@22.1.1:24)
14:58:55.220  W  	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
14:58:55.220  W  	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
14:58:55.220  W  	at android.os.Handler.dispatchMessage(Handler.java:106)
14:58:55.220  W  	at android.os.Looper.loopOnce(Looper.java:201)
14:58:55.220  W  	at android.os.Looper.loop(Looper.java:288)
14:58:55.220  W  	at android.app.ActivityThread.main(ActivityThread.java:7918)
14:58:55.220  W  	at java.lang.reflect.Method.invoke(Native Method)
14:58:55.220  W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
14:58:55.220  W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
14:58:55.261  W  Expecting binder but got null!
```

### Please specify the version of Windows Subsystem for Android
2307.40000.6.0

Also opened in Firebase Android SDK https://github.com/firebase/firebase-android-sdk/issues/5355

**Comment by kevinkieselbach** [comment]
As mentioned in the linked Firebase discussion, this is probably an issue with WSA's heuristics for identifying authentication URLs.  @xanscale, please provide the authentication URL passed to the browser in your scenario, and we'll see if we can update our heuristics to handle it.

**Comment by xanscale** [comment]
i'm only third party developer, we need @argzdev

anyway should be useful a way to force the behavior, like a flag in manifest

**Comment by xanscale** [comment]
https://github.com/firebase/firebase-android-sdk/issues/5355#issuecomment-1755505257

**Comment by kevinkieselbach** [comment]
I updated WSA's heuristics to handle the Firebase authentication URLs.  The fix should go out with WSA's 2311 build.

**Comment by xanscale** [comment]
@kevinkieselbach now with WSA's 2311 build use internal webivew (instead of windows browser) but crash at the end of webview flow

```
com.google.firebase.auth.FirebaseAuthWebException: The web operation was canceled by the user.
 at com.google.android.gms.internal.firebase-auth-api.zzaas.zza(com.google.firebase:firebase-auth@@22.1.1:11)
 at com.google.firebase.auth.internal.zzav.onReceive(com.google.firebase:firebase-auth@@22.1.1:24)
 at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
 at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7918)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d2bdae6, Dispatchers.Main.immediate]
```
